class CommonStrings{   
    static a = 'check';
    static localStorageStrings = {        
        theme: {
            mode: 'mode',
            lightMode: 'light',
            darkMode: 'dark'
        },
        searchLocalStorageStrings : {
            quickSearchType: 'Quick',
            advancedSearchType: 'Advanced',
            lastSearchSource: 'lastSearchSource',
            lastQuickSearch: 'lastQuickSearch',            
            chosenOrganisms: 'chosenOrganismsSearch',
            chosenDatasetName: 'chosenDatasetsNamesSearch',            
            chosenSeedFamilies: 'chosenSeedFamiliesSearch',
            chosenMiRnaIds: 'chosenMiRnaIdsSearch',
            chosenSites : 'chosenSitesSearch',
            chosenGeneIds: 'chosenGeneIdsSearch',
            setChosenRegions: 'setChosenRegionsSearch',            
            results: 'searchResults',
            chosenFeature : 'chosenFeatureSearch',
            chosenFilter : 'chosenFilterSearch',
            setChosenFeature : 'setChosenFeatureSearch',
            chosenFilterValue : 'chosenFilterValueSearch',
            chosenFeatures : 'chosenFeaturesSearch',
            relevantFeatures : 'relevantFeaturesSearch'
        },

        browseLocalStorageStrings : {
            chosenOrganism: 'chosenOrganismsBrowse',
            chosenDatasetName : 'chosenDatasetNameBrowse',
            results: 'browseResults',
        },
        statisticsLocalStorage: {
            mainStatistics: 'mainStatistics'
        }
    };

    static apiStrings = {
        consoleExceptions: {
            browse: 'exception at browse',
            search: 'exception at search',
            download: 'exception at download',
            interaction: 'exception at interaction page',
            details: 'exception for getting details',
            requestNotGood: 'search query is empty',
        },
        userExceptions: {
            generalErrorTitle: 'Something went wrong',
            generalErrorDescription: 'fetching from server failed',
        },
        userInfo: {
            moreResultsTitle: 'There might be more records',
            moreResultsDescription: 'We are showing only 750 records, feel free to download',

        }
    };
    
    static mappingStrings = {
        interaction : "interaction",
        interactionMap : "Interaction",
        miRna: "miRna",
        miRnaMap: "miRNA",
        mRna: "mRna",
        mRnaMap: "mRNA",
        organisms: "organisms",
        organismsMap: 'Organisms',
        datasets: "datasets",
        datasetsMap: 'Datasets',
        seedFamilies: 'seedFamilies',
        seedFamiliesMap: 'Seed-Families',
        miRnaIds: 'miRnaIds',
        miRnaIdsMap: 'miRNA-Ids',
        sites: 'sites',
        sitesMap: 'Sites',
        site: 'site',
        siteMap: 'Site',
        geneIds: 'geneIds',
        geneIdsMap: 'Gene-Ids',
        regions: 'regions',
        regionsMap: 'Regions',        
        mirnaSequence: 'mirnaSequence',
        mirnaSequenceMap: 'MiRNA-Seq',
        features: 'features',
        featuresMap: 'Feature',
        index : 'index',
        indexMap : 'Id in dataset',
        interactionId : 'interactionId',
        interactionIdMap : 'Pair Id',
        datasetName: 'datasetName',
        datasetNameMap: 'Dataset',
        miRnaId : 'miRnaId',
        miRnaIdMap : ' miRNA Id',
        miRnaSeq : 'miRnaSeq',
        miRnaSeqMap : 'miRNA seq',
        seedFamily :'seedFamily',
        seedFamilyMap :'miRNA seed family',
        siteType : 'siteType',
        siteTypeMap : 'Site Type',
        siteTypes : 'site types',
        siteTypesMap : 'Site Types',
        region : 'region',
        regionMap : 'Region',
        interStart : 'interStart',
        interStartMap : 'Interaction Start',
        start : 'start',
        startMap : 'Start',
        end : 'end',
        endMap : 'End',
        interEnd : 'interEnd',
        interEndMap : 'Interaction End',
        mrnaBulge : 'mrnaBulge',
        mrnaBulgeMap : 'MRNA Bulge',
        mrnaInter : 'mrnaInter',
        mrnaInterMap : 'MRNA Inter',
        mirInter : 'mirInter',
        mirInterMap : 'MiRNA Inter',
        mirBulge : 'mirBulge',
        mirBulgeMap : 'MiRNA Bulge',
        energyMefDuplex : 'energyMefDuplex',
        energyMefDuplexMap : 'Duplex MFE',
        featureTypes : 'featureTypes',
        featureTypesMap : 'Feature Types',
        filters : 'filters',
        filtersMap : 'Filters',
        featuresData : 'featuresData',
        featuresDataMap : 'Features Data',
        geneId : 'geneId',
        geneIdMap : 'Gene Id',
        geneName : 'geneName',
        geneNameMap : 'Gene Name',
        sequenceUrl: 'sequenceUrl',
        sequenceUrlMap: 'Link for more',
        dataSource: 'dataSource',
        dataSourceMap: 'Data Source',
        duplexStructure: 'duplexStructure',
        duplexStructureMap: 'Duplex Structure',
        mRnaDistToEnd: 'mRnaDistToEnd',
        mRnaDistToEndMap: 'mRNA Distance To End',
        mRnaDistToStart: 'mRnaDistToStart',
        mRnaDistToStartMap: 'mRNA Distance To Start',
        seedMatchCanonical: 'seedMatchCanonical',
        seedMatchCanonicalMap: 'Seed Match Canonical',
        seedMatchNonCanonical: 'seedMatchNonCanonical',
        seedMatchNonCanonicalMap: 'Seed Match Non-Canonical',
        seedMatchStart: 'seedMatchStart',
        seedMatchStartMap: 'Seed Match Start',
        interactionInnerData: 'interactionInnerData',
        interactionInnerDataMap: 'Interaction Data',
        miRnaData: 'miRnaData',
        miRnaDataMap: 'Micro RNA Data',
        mRnaData: 'mRnaData',
        mRnaDataMap: 'Message RNA Data',
        miRnaSequence: 'miRnaSequence',
        miRnaSequenceMap: 'miRNA Sequence',
        organismName: 'organismName',
        organismNameMap: 'Organism',                
        advancedSearch: 'advanced',
        advancedSearchMap: 'Advanced Search',
        quickSearch: "quickSearch",
        quickSearchMap: 'Quick Search'
    };

    static headCellsToHide = ["start", "end", "mrnaBulge", "mrnaInter", "mirInter", "mirBulge"];
}
export default CommonStrings;