import { Box, Typography } from '@mui/material';
import image from './../extensions/images/homepage-images/about.jpg';
import React from 'react';

const About = () => {
  const aboutText = `MiRNAs are short non-coding RNA molecules that act as post-transcriptional regulators of gene expression by base-paring with target mRNAs, playing a significant role in the regulation of various cellular functions. We collected datasets of bonafide miRNA-mRNA interactions generated by high-throughput experiments (e.g., CLASH, see Table below), and annotated each interaction with an interaction duplex and a set of features (e.g., duplex energy, duplex structure, target site composition, and target site context). Using these datasets, we generated powerful machine-learning (ML) models to promote the prediction of new interactions. Recognizing the need to introduce this valuable data and the powerful ML capabilities to the wider scientific community, we conceived this website as a welcoming and convenient hub for the research community. Our platform serves as a one-stop-shop, providing a comfortable space`;
  return (
    <Box
      display='grid'
      gridTemplateColumns={{ xs: 'repeat(1, 1fr)', md: 'repeat(2, 1fr)' }}
      gap={2}
    >
      <Box sx={{ margin: '2vh', paddingTop: { md: '2vh' } }}>
        <Box
          sx={{
            width: '60%',
            marginLeft: '20vh',
            margin: 'auto',
          }}
        >
          <img
            style={{
              borderRadius: '2%',
              boxShadow: '0 6px 20px 0 rgba(0, 0, 0, 0.5)',
            }}
            src={image}
            width={'100%'}
            height={'100%'}
            alt=''
          />
          
        </Box>
      </Box>
      
      <Box sx={{ margin: '2vh', paddingTop: { md: '3vh' } }}>
        <Typography
          color={'primary'}
          sx={{
            fontSize: {
              xs: 'x-small',
              md: 'medium',
              lg: '75%',
              xl: '120%',
            },
          }}
        >
          {aboutText}
        </Typography>
      </Box>
    </Box>
  );
};

export default About;
